version: '2'
services:
  httpd:
    image: reflet/docker-apache2.4
    container_name: 'httpd'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - app-data:/var/www/www.example.com/
      - ./compose/httpd/ssl:/usr/local/apache2/conf.d/virtualhost/ssl
      - ./compose/httpd/www.example.com.conf:/usr/local/apache2/conf.d/virtualhost/www.example.com.conf

  php:
    build: .
    image: my/php7.2
    container_name: 'php'
    ports:
      - '9000:9000'
    volumes:
      - app-data:/var/www/www.example.com/

  node:
    image: reflet/docker-node9.11
    container_name: 'node'
    tty: true
    volumes:
      - app-data:/var/www/www.example.com/

  mysql:
    image: reflet/docker-mysql5.7
    container_name: 'mysql'
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_ROOT_PASSWORD=development
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./compose/mysql/example.sql:/docker-entrypoint-initdb.d/example.sql

  postgres:
    image: reflet/docker-postgres9.1
    container_name: 'postgres'
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:development
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ./compose/postgres/example.sql:/docker-entrypoint-initdb.d/example.sql

  redis:
    image: reflet/docker-redis4.0
    container_name: 'redis'
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"

volumes:
  app-data:
    driver_opts:
      type: none
      device: ${PWD}/src/
      o: bind
  mysql-data:
    driver: local
  postgres-data:
    driver: local
